#FirstName = "James"
#MiddleName = "john"
/ThirdName = "simon"
,otherName = "ragnar"
.LastName = "ivar the boneless"
1234firstName = "Bjorn ironside"
1234otherName = "Merlin"
1234thirdName = "Ultred"
1234middleName = "Morgana"
1234firstName = "Gauis"

-middle_name = "Barry"
-other_name = "Allen"
-third_name = "Clark"
{last_name = "Kent"
[second_name = "Authur"   
